FROM node:16-slim AS build
WORKDIR /app
RUN useradd -m appuser
COPY package*.json tsconfig.json /app/
RUN npm install --production --silent
COPY . /app/
RUN npm install -g typescript && tsc

FROM node:16-slim AS runtime
WORKDIR /app
RUN useradd -m appuser
COPY --from=build /app/dist /app/dist
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/package.json /app/
RUN chown -R appuser:appuser /app
USER appuser
EXPOSE 4000
CMD ["node", "dist/index.js"]
