FROM node:16-slim AS build
WORKDIR /app
RUN useradd -m appuser
COPY package*.json tsconfig.json ./
RUN npm ci --production --silent
COPY . .
RUN npx tsc

FROM node:16-slim AS runtime
WORKDIR /app
RUN useradd -m appuser
COPY --from=build /app/dist dist
COPY --from=build /app/node_modules node_modules
COPY --from=build /app/package.json .
USER appuser
EXPOSE 4000
CMD ["node", "dist/index.js"]
